const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_LOADING_PAGE: 'SET_LOADING_PAGE',

    //music
    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
    SET_CURRENT_SONG_DATA: 'SET_CURRENT_SONG_DATA',
    SET_CURRENT_ALBUM_ID: 'SET_CURRENT_ALBUM_ID',
    SET_PLAYING_RAND: 'SET_PLAYING_RAND',
    SET_PLAYING: 'SET_PLAYING',
    SET_LOADING_SONG: 'SET_LOADING_SONG',
    SET_VOLUME: 'SET_VOLUME',
    SET_LIST_SONGS: 'SET_LIST_SONGS',
    SET_RECENT_SONGS: 'SET_RECENT_SONGS',
    SET_WEEK_CHART: 'SET_WEEK_CHART',
    DELETE_RECENT_SONGS: 'DELETE_RECENT_SONGS',
    SEARCH: 'SEARCH',

    //sidebar right
    SET_OPEN_SIDE_BAR_RIGHT: 'SET_OPEN_SIDE_BAR_RIGHT',
};

export default actionTypes;
